### ISSUE TITLE
bash: syntax error near unexpected token `newline'

### ISSUE THREAD

**Issue by shahrooz1349** [StdCarrot/iamovpn#7] opened 2022-08-15 11:22 UTC
Thanks for the admin panel 
![Screenshot_20220815_155219](https://user-images.githubusercontent.com/87688187/184626640-6b551fa7-3bc6-4b99-9853-cf6936b2007b.jpg)
I got this error while installing Ubuntu 18.04

**Comment by StdCarrot** [comment] 2022-08-15 18:17
OK, you type `<path/to/config.json>`.  
But, it's wrong.  
You have to create your own `config.json` from `config.json.dist`.
And set a path for the `config.json` into the position.  
Generally, `<something>` means that you need to set your own `something`. 
this is not a bug, so I'll close this issue.

**Closed by StdCarrot** 2022-08-15 18:17 UTC

**Comment by shahrooz1349** [comment] 2022-08-16 08:55
Thank you, dear developer 🙏🌹

**Comment by shahrooz1349** [comment] 2022-08-16 11:26
@StdCarrot  Unfortunately, I also changed the location, but the problem remains

**Comment by shahrooz1349** [comment] 2022-08-16 19:37
@StdCarrot I am new to this field I failed to use your script The problem still exists Can you give some more guidance? 
With respect

**Comment by shahrooz1349** [comment] 2022-08-16 21:18
@StdCarrot  I used Ubuntu 18.04 as per your recommendation
I have this error after the installation command
"python3 iamovpn install --config /root/iamovpn/config.json"

regard
![Screenshot_20220817_013430_org connectbot_edit_106003057706741](https://user-images.githubusercontent.com/87688187/184986933-0dea7e6a-d393-46cb-a4da-50278ba4f788.jpg)
